#!/bin/bash
set -e -u -o pipefail
cd "$(dirname "$0")"
export OCAMLMIG_TEST=
function ocamlmig {
    ../_build/default/bin/main.exe "$@"
}
eval $(dune tools env) # put ocamlformat in scope
ocamlmig migrate test_migration.ml test_mli.mli "$@"
ocamlmig migrate -module-migration test_migration_module.ml "$@"
ocamlmig transform rescope -unqualify Z test_scope_unqualify.ml "$@"
ocamlmig transform rescope -unopen Z test_scope_unopen.ml "$@"
ocamlmig transform rescope -open Z test_scope_open.ml "$@"
ocamlmig transform migration-inverse test_migration_inverse.ml "$@"
ocamlmig check test_migration_check.ml{,i} "$@"
ocamlmig replace *.ml "$@"
ocamlmig internal record-result test_attribute.ml "$@" -- migrate
(unset OCAMLMIG_TEST # rewrites are disabled when under the test extension node otherwise
 ocamlmig internal record-result test_preserve_format.ml "$@" -record-snapshot \
          -- replace -format preserve  \
          -e 'Fun.id __e /// __e' \
          -e '"hello" /// (); "hello"'
 ocamlmig internal record-result test_preserve_format_open.ml "$@" -record-snapshot \
          -- tr rescope -format preserve -open Format
 ocamlmig internal record-result test_preserve_format_unopen.ml "$@" -record-snapshot \
          -- tr rescope -format preserve -unopen Format
)
ocamlmig check ../examples/stdlib_to_base/stdlib_to_base.ml

if false; then
    unset OCAMLMIG_TEST
    cp ../examples/stdlib_to_base/stdlib_to_base.ml ../examples/base_to_stdlib/base_to_stdlib.ml
    for m in $(grep -o 'open .*' ../examples/base_to_stdlib/base_to_stdlib.ml | cut -f 2 -d ' ' | sort -u | grep -v struct); do sleep 0.3; ocamlmig transform rescope -unopen $m ../examples/base_to_stdlib/base_to_stdlib.ml -w; done
    sleep 0.3
    ocamlmig transform migration-inverse ../examples/base_to_stdlib/base_to_stdlib.ml -w
fi
